# Generated by Django 6.0.3 on 2026-03-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.IntegerField(),
        ),
    ]
