# Generated by Django 6.0.3 on 2026-03-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='page_no',
        ),
    ]
