# Generated by Django 6.0.3 on 2026-03-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owasptop10',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
