# Generated by Django 6.0.3 on 2026-03-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_owasptop10_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='owasptop10',
            name='attack_scenarios',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='owasptop10',
            name='prevention',
            field=models.JSONField(default=list),
        ),
    ]
