# Generated by Django 6.0.3 on 2026-03-20 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_owasptop10_attack_scenarios_owasptop10_prevention'),
    ]

    operations = [
        migrations.AddField(
            model_name='owasptop10',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
