# Generated by Django 6.0.3 on 2026-03-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_owasptop10_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='owasptop10',
            name='page_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
